project_id = "wrhcgufugnyquufydvwl"

[functions.create-nostr-profile]
verify_jwt = false

[functions.send-lana-to-players]
verify_jwt = false

[functions.get-available-prizes]
verify_jwt = false

[functions.retry-failed-transactions]
verify_jwt = false